// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmxRuV-jUe4LZhdZOeOVsVHJ5skldW-Cg',
    appId: '1:69939864084:web:17537474a4534a120e7d01',
    messagingSenderId: '69939864084',
    projectId: 'better-eat-that-70e93',
    authDomain: 'better-eat-that-70e93.firebaseapp.com',
    storageBucket: 'better-eat-that-70e93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSUWIyjFBVqcsq88X8cjudZt7XNYpm2JQ',
    appId: '1:69939864084:android:dee08efc449d27ec0e7d01',
    messagingSenderId: '69939864084',
    projectId: 'better-eat-that-70e93',
    storageBucket: 'better-eat-that-70e93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy_dhyTOLvGt2MOho41HrTklIcY0vjb_E',
    appId: '1:69939864084:ios:c0d35e3767a2c92f0e7d01',
    messagingSenderId: '69939864084',
    projectId: 'better-eat-that-70e93',
    storageBucket: 'better-eat-that-70e93.appspot.com',
    iosBundleId: 'com.example.bet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy_dhyTOLvGt2MOho41HrTklIcY0vjb_E',
    appId: '1:69939864084:ios:6ca274c15dbb137b0e7d01',
    messagingSenderId: '69939864084',
    projectId: 'better-eat-that-70e93',
    storageBucket: 'better-eat-that-70e93.appspot.com',
    iosBundleId: 'com.example.bet.RunnerTests',
  );
}
